# Generated by Django 3.2.7 on 2021-09-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('All', 'All'), ('S', 'Sport'), ('SW', 'Sport wear'), ('OW', 'Outerwear')], max_length=3),
        ),
    ]
