# Generated by Django 3.2.7 on 2021-09-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('All', 'All'), ('Outerwear', 'Outerwear'), ('Shirt', 'Shirt'), ('Sport', 'Sport'), ('Sportwear', 'Sport wear')], max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('D', 'danger'), ('P', 'primary'), ('S', 'secondary')], max_length=1),
        ),
    ]
