# Generated by Django 3.2.7 on 2021-09-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210907_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
