# Generated by Django 3.2.7 on 2021-09-07 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_item_price_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_discount',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]))]),
        ),
    ]
