# Generated by Django 3.2.7 on 2021-09-07 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_item_foo_price_range'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='foo_price_range',
        ),
    ]
