# Generated by Django 3.2.7 on 2021-09-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_item_foo_price_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='this is a test description'),
            preserve_default=False,
        ),
    ]
