# Generated by Django 3.2.7 on 2021-09-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='image_missing.jpg', upload_to='inventory_pics'),
        ),
    ]
