# Generated by Django 3.2.7 on 2021-09-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20210915_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_charge_obj',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
