# Generated by Django 3.2.7 on 2021-09-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_payment_stripe_charge_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.BigIntegerField(default=2),
            preserve_default=False,
        ),
    ]
