# Generated by Django 3.2.7 on 2021-09-16 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_payment_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='payment',
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.payment'),
        ),
    ]
