# Generated by Django 3.2.7 on 2021-09-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount_value',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
    ]
