# Generated by Django 3.2.7 on 2021-09-28 07:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_coupon_discount_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='date_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='date_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_uom',
            field=models.CharField(choices=[('percent', 'percent'), ('absolute', 'absolute')], default='absolute', max_length=20),
            preserve_default=False,
        ),
    ]
