# Generated by Django 3.2.7 on 2021-10-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0015_alter_address_address2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
