# Generated by Django 3.2.7 on 2021-10-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0016_alter_address_address2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('All', 'All'), ('Outerwear', 'Outerwear'), ('Shirt', 'Shirt'), ('Sport', 'Sport'), ('Sport wear', 'Sport wear')], max_length=30),
        ),
    ]
